"Filed out from Dolphin Smalltalk 7"!

RowanProjectService subclass: #RowanResolvedProjectService
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanResolvedProjectService guid: (GUID fromString: '{a8e74b3d-49f3-45fc-b281-23ee7f83cb31}')!
RowanResolvedProjectService comment: ''!
!RowanResolvedProjectService categoriesForClass!Unclassified! !
