"Filed out from Dolphin Smalltalk 7"!

RowanService subclass: #RowanComponentService
	instanceVariableNames: 'name componentServices packageServices projectService'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanComponentService guid: (GUID fromString: '{842be73b-a371-499f-a6d4-dcd4a81c01e5}')!
RowanComponentService comment: ''!
!RowanComponentService categoriesForClass!Unclassified! !
!RowanComponentService methodsFor!

displayString
	^name!

name
	^name! !
!RowanComponentService categoriesFor: #displayString!displaying!public! !
!RowanComponentService categoriesFor: #name!accessing!public! !

