Class {
	#name : 'RowanMonticelloRepositoryService',
	#superclass : 'RowanService',
	#instVars : [
		'description'
	],
	#category : 'Rowan-Services-Core'
}

{ #category : 'as yet unclassified' }
RowanMonticelloRepositoryService class >> templateClassName [

	^#'RowanMonticelloRepositoryService'

]

{ #category : 'accessing' }
RowanMonticelloRepositoryService >> description [
	^description

]

{ #category : 'accessing' }
RowanMonticelloRepositoryService >> description: object [
	description := object

]
